# Are you providing the output of a combined featurecounts or kallisto output?
# If providing kallisto then set to True and provide path to the kallisto quant dir
kallisto: True
kallisto_dir: "~/Documents/PROJECTS/proj035/pseudobulk-test/quant/"

# Specify if mouse or human
species: "mouse"
