---
title: "Enrichment"
output: html_document
---

```{r, include=FALSE}
library(XGR)
library(DT)
```


# MV vs EX

## Reactome

```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}

ontology <- "MsigdbC2REACTOME"

background <- as.vector(read.csv("results/MVvsEX_res.csv")$SYMBOL)

data <- as.vector(read.csv("results/MVvsEX_sig.csv")$SYMBOL)

eTerm <- xEnricherGenes(data=data, background=background, ontology=ontology)
eTerm <- xEnrichConciser(eTerm)
datatable(xEnrichViewer(eTerm, 20))
```

### Bar plot of the enrichment

```{r,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}

bp <- xEnrichBarplot(eTerm, top_num="auto", displayBy="adjp")
print(bp)
```

## KEGG

```{r,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}

ontology <- "MsigdbC2KEGG"

background <- as.vector(read.csv("results/MVvsEX_res.csv")$SYMBOL)

data <- as.vector(read.csv("results/MVvsEX_sig.csv")$SYMBOL)

eTerm <- xEnricherGenes(data=data, background=background, ontology=ontology)
eTerm <- xEnrichConciser(eTerm)
datatable(xEnrichViewer(eTerm, 20))
```

### Bar plot of the enrichment

```{r,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}

bp <- xEnrichBarplot(eTerm, top_num="auto", displayBy="adjp")
print(bp)
```

# GDMvsNORM

## Reactome

```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}

ontology <- "MsigdbC2REACTOME"

background <- as.vector(read.csv("results/GDMvsNORM_res.csv")$SYMBOL)

data <- as.vector(read.csv("results/GDMvsNORM_sig.csv")$SYMBOL)

eTerm <- xEnricherGenes(data=data, background=background, ontology=ontology)
eTerm <- xEnrichConciser(eTerm)
datatable(xEnrichViewer(eTerm, 20))
```

### Bar plot of the enrichment

```{r,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}

bp <- xEnrichBarplot(eTerm, top_num="auto", displayBy="adjp")
print(bp)
```

## KEGG

```{r,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}

ontology <- "MsigdbC2KEGG"

background <- as.vector(read.csv("results/GDMvsNORM_res.csv")$SYMBOL)

data <- as.vector(read.csv("results/GDMvsNORM_sig.csv")$SYMBOL)

eTerm <- xEnricherGenes(data=data, background=background, ontology=ontology)
eTerm <- xEnrichConciser(eTerm)
datatable(xEnrichViewer(eTerm, 20))
```

### Bar plot of the enrichment

```{r,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}

bp <- xEnrichBarplot(eTerm, top_num="auto", displayBy="adjp")
print(bp)
```