---
title: "GSEA"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
library(msigdbr)
library(fgsea)
#library(multiGSEA)
library(EGSEA)
knitr::opts_chunk$set(echo = TRUE)

source('functions.R')
library(kableExtra)
library(stringr)
library(dplyr)
library(ggpubr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE, message=FALSE)
```

```{r yaml, echo=TRUE,warning=FALSE,message=FALSE,error=FALSE, include=FALSE}
params <- read_yaml("config.yml")

if(params$kallisto){
design_files <- list.files(path="designs_kallisto/", pattern = "design_")}else{
  design_files <- list.files(path='designs_featurecounts/', pattern = "design_")
}
```

# GSEA rank list

```{r}
for (i in design_files){
  res_name <- sub('.csv', '', i, perl = TRUE)
  res_name = paste("results/", res_name,"_annotate_res.csv", sep="")
  if(file.exists(res_name)){
    results_annotated = read.csv(res_name)
    dir.create("results_rnk/", showWarnings = FALSE)
    results_dir = paste("results_rnk/", i,".rnk", sep="")
    gsea_rnk(results_annotated=results_annotated, results_dir=results_dir)
  }

  
}
```

# GSEA run 

```{r}
for (i in design_files){
  
pathways <- "Hallmark"
title = gsub(".csv","",i)
res_name <- sub('.csv', '', i, perl = TRUE)
res_name = paste("results/", res_name,"_annotate_res.csv", sep="")
  dir.create("results_gsea/", showWarnings = FALSE)

  
  skip_to_next <- FALSE
  
  # Note that print(b) fails since b doesn't exist
  
  if(file.exists(res_name)){
  print(i)
  results_dir = read.csv(res_name)  
  tryCatch(print(GSEA_plots(pathways, title, results_dir)), error = function(e) { skip_to_next <<- TRUE})}
  
  if(skip_to_next) { next }   
  
    
  
    
    

}

```