---
title: "Enrichment"
output: 
  html_document:
    code_folding: hide
---

```{r, include=FALSE}
source('functions.R')
library(Pi)
library(DT)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='asis')
```


# Reactome


```{r,warning=FALSE,message=FALSE,error=FALSE}

files <- Sys.glob("results/*sig.csv")

for (i in files) {

  name <-  gsub(".csv","",i)
  name <-  gsub("results/","",name)
  sig <- read.csv(file=as.character(i))
  ontology <- "MsigdbC2REACTOME"
  res <-  gsub("_sig.csv","",i)
  res <- paste0(res, "_res.csv")
  background <- as.vector(toupper(read.csv(res)$SYMBOL))

  data <- as.vector(toupper(read.csv(i)$SYMBOL))

  eTerm <- xEnricherGenes(data=data, background=background, ontology=ontology)
  
  dir.create(file.path("enrichment_XGR"), showWarnings = FALSE)
  dir.create(file.path("enrichment_XGR", ontology), showWarnings = FALSE)
  output <- paste0("enrichment_XGR","/", ontology, "/", name, ".csv")
  write.csv(file=as.character(output), as.data.frame(xEnrichViewer(eTerm)))
  assign(paste("eTerm", i, sep = "."), eTerm)
  }
```

### Bar plot of the enrichment {.tabset .tabset-fade}

```{r,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}
for (i in files) {
  eTerm <- get(gsub("SAMPLE_FILE",i , "eTerm.SAMPLE_FILE"))
  bp <- xEnrichBarplot(eTerm, top_num="auto", displayBy="adjp")
  name <-  gsub(".csv","",i)
  
  cat("#### ",name,"\n")
  print(bp)
  cat('\n\n')
}

```

## KEGG

```{r,warning=FALSE,message=FALSE,error=FALSE}

files <- Sys.glob("results/*sig.csv")

for (i in files) {

  name <-  gsub(".csv","",i)
  name <-  gsub("results/","",name)
  sig <- read.csv(file=as.character(i))
  ontology <- "MsigdbC2KEGG"
  res <-  gsub("_sig.csv","",i)
  res <- paste0(res, "_res.csv")
  
  background <- as.vector(toupper(read.csv(res)$SYMBOL))

  data <- as.vector(toupper(read.csv(i)$SYMBOL))
  
  eTerm <- xEnricherGenes(data=data, background=background, ontology=ontology)
  
  dir.create(file.path("enrichment_XGR", ontology), showWarnings = FALSE)
  output <- paste0("enrichment_XGR","/", ontology, "/", name, ".csv")
  write.csv(file=as.character(output), as.data.frame(xEnrichViewer(eTerm)))
  assign(paste("eTerm", i, sep = "."), eTerm)
  }
```

### Bar plot of the enrichment {.tabset .tabset-fade}

```{r,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='asis'}
for (i in files) {
  eTerm <- get(gsub("SAMPLE_FILE",i , "eTerm.SAMPLE_FILE"))
  bp <- xEnrichBarplot(eTerm, top_num="auto", displayBy="adjp")
  name <-  gsub(".csv","",i)
  cat("####",name,"\n")
  print(bp)
  cat('\n\n')
}
```
